#version: '3'

services:
  nats-server:  
    image: nats:latest

  client-gateway: 
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/robotic-sector-447122-n9/checklist/client-gateway-ms:v1.1.3
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:  
      PORT: ${CLIENT_GATEWAY_PORT}
      NATS_SERVERS: nats://nats-server:4222
    #volumes:
    #  - ./client-gateway:/src:/usr/src/app/src
    
  auth_microservice: 
    build:
      context: ./auth_microservice
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/robotic-sector-447122-n9/checklist/auth-microservice:v1.1.3
    ports:
      - "3004:3004"
    environment:  
      PORT: 3004
      NATS_SERVERS: nats://nats-server:4222
      DATABASE_URL: ${DATABASE_URL}

  edificio_microservice: 
    build:
      context: ./edificios
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/robotic-sector-447122-n9/checklist/edificio-microservice:v1.0.2
    ports:
      - "3002:3002"
    environment:  
      PORT: 3002
      NATS_SERVERS: nats://nats-server:4222

  aulas_microservice: 
    build:
      context: ./aulas
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/robotic-sector-447122-n9/checklist/aulas-microservice:v1.0.2
    ports:
      - "3005:3005"
    environment:  
      PORT: 3005
      NATS_SERVERS: nats://nats-server:4222

  cuarto_servicio: 
    build:
      context: ./cuarto-servicio
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/robotic-sector-447122-n9/checklist/cuarto-servicio-microservice:v1.0.1
    ports:
      - "3006:3006"
    environment:  
      PORT: 3006
      NATS_SERVERS: nats://nats-server:4222

  informes_microservice: 
    build:
      context: ./informe
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/robotic-sector-447122-n9/checklist/informe-microservice:v1.0.1
    ports:
      - "3007:3007"
    environment:  
      PORT: 3007
      NATS_SERVERS: nats://nats-server:4222
