apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-gateway
    spec:
      containers:
      - image: northamerica-south1-docker.pkg.dev/robotic-sector-447122-n9/checklist/client-gateway-ms:v1.1.3
        name: client-gateway-ms
        env:
        - name:  PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        resources:
          requests:
            memory: "256Mi" # Memoria garantizada
            cpu: "250m"    # CPU garantizada
          limits:
            memory: "512Mi" # Máxima memoria permitida
            cpu: "500m" 
status: {}
