apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checklist-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - checklistutpl.duckdns.org
      secretName: checklist-tls # Secret name for the TLS certificate
  rules:
    - host: checklistutpl.duckdns.org
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: client-gateway
              port:
                number: 3000
